name: GitHub pages

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: documentation.js
        run: |
          npm install -g documentation
          documentation build src/** -f html --github -o docs
     
      - name: push back
        run:
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/**
          git commit -m "[actions] update docs"
          git push
